### ISSUE TITLE
Parser should parse copycodes in the context where they are INCLUDEd

### ISSUE THREAD

**Issue by Claes65** [MarkusAmshove/natls#125]
Right now, a CC is parsed as any other Natural Module. But it need to be parsed in the context where is it called (INCLUDEd): Eg.

INCLUDE SE----AC                          
  PN.INSTRUKTION := &1&                   
  CALLNAT 'SE--GIAF' PN T-OBJEKT ZXINFOPA 
  PN.INSTRUKTION := PNK.INSTRUKTION       
ELSE                                      
  ....

The CopyCode, SE----AC just contains: "IF TRUE" - this forces an exception because the CC itself cannot be parsed.

**Comment by MarkusAmshove** [comment]
This will make it possible to also see references like this to modules which are called by copycodes where the module name is constructed by a copycode parameter

**Comment by MarkusAmshove** [comment]
Note: Could do additional Lexer passes, where the `NaturalParser` processes the `TokenList` and adds the Tokens after the include. These new tokens will come from a Lexer run over the copycode, knowing how to replace copy code parameters.
Be aware of stackoverflows for recursive copycodes.

**Comment by Claes65** [comment]
Substituting the parameters for sure helped a lot, but be aware that the code snip I mention still does not pass. To fully pass copycodes, the only thing to do is to internally insert the source of the copy code (and all nested cc) into the calling source while replacing the parameters.

**Comment by Claes65** [comment]
After fixing exceptions, I get new diagnostics related to this. 

INCLUDE SOMECC
SOMECC contains another INCLUDE IFTRUE and this only contains IF TRUE (made so you could change this to IF FALSE and re-compile)

INCLUDE IFTRUE
  statements
ELSE
  statements
END-IF

Getting:
NPP030;ERROR;Missing closing END_IF for IF
NPP043;ERROR;Statement must have a body. Add IGNORE if body should be empty.
