### ISSUE TITLE
Link variables in views to their fields in DDMs

### ISSUE THREAD

**Issue by MarkusAmshove** [MarkusAmshove/natls#15]
Maybe create a new type of variable derived from `ITypedVariableNode` that has all the information from the variable of the DDM (e.g. the type).
If the type is overwritten in the view, have it be a default `ITypedVariableNode`.

Diagnostics:
- If the length in the view is greater than the length in the DDM for the field, report an error
- #157 

- [ ] Closes #190 
Note that the VIEW can declare a different type
- [ ] Remove the exclusion of REDEFINEs from VIEWS in `DataDefinitionParser::checkRedefineLength()`
- [ ] The view variable itself also has a length and can be redefined. The length is the same is it is for groups (the sum of its child variables)
- [ ] Look for usages of `isInView()` and fix the workarounds

**Comment by MarkusAmshove** [comment]
When the type is known or the variable is somehow linked to the ddm variable, fix the TODO in `CompressAnalyzer`.

**Comment by Claes65** [comment]
Note, that a variable in a DDM can also be a group. We have a "normal" group and a periodic group. @MarkusAmshove
