### ISSUE TITLE
Turn off BooleanOperatorAnalyzer by default

### ISSUE THREAD

**Issue by MarkusAmshove** [MarkusAmshove/natls#281]
Currently the BooleanOperatorAnalyzer wants to enforce everyone to use sign style operators by default.
Thats just one style that fits some companies but not others.

After a meeting with Claes, we came to the conclusion that all analyzers about code style (`natls.style.*` settings) should be off by default.

So the new possible settings should be:

```
natls.style. comparisons=false # default
natls.style. comparisons=short
natls.style. comparisons=sign
```

**Comment by Claes65** [comment]
@MarkusAmshove - working on this.

**Comment by MarkusAmshove** [comment]
I misread the working on :)
