### ISSUE TITLE
Bug: DECIDE condition where special MOVE EDITED is used

### ISSUE THREAD

**Issue by Claes65** [MarkusAmshove/natls#340]
The MOVE EDITED seems to mess with the condition.

![image](https://github.com/MarkusAmshove/natls/assets/105717036/443cd876-b47e-4d8b-947c-c551b30881d2)

**Comment by Claes65** [comment]
DEFINE DATA
PARAMETER
1    PARM
  2  GÆLDER-FRA-DATO           (D)
  2  GÆLDER-FRA-DATO-FJL       (L)
  2  GÆLDER-FRA-DATO-GL        (D)
  2  VALG-KODE (A01)
LOCAL
1 W-FGR (N3)
1 SDTRANSA
  2 POLI-FINDES (L)
END-DEFINE
DECIDE FOR FIRST CONDITION
  WHEN W-FGR = 655 OR = 653
    MOVE EDITED PARM.GÆLDER-FRA-DATO-GL (EM=DD-MM-YYYY').') TO ZX-TEKST
  WHEN (W-GL-STATUS = 'POLI' OR = 'TILB') AND PARM.VALG-KODE = 'P'
    ASSIGN POLI-FINDES = TRUE
  WHEN NONE
    IGNORE
END-DECIDE
END

**Comment by Claes65** [comment]
Getting same diagnostic for same MOVE EDITED construction in these statements:

  MOVE EDITED W-WORK-DATO-D (EM=DD-MM-YYYY').') TO ZX-TEKST
  IF SZVAH2AA.POLICE-VARIANT-STATUS (W-IX) = 'XXXX'

**Comment by MarkusAmshove** [comment]
The `EM=` doesn't terminate correctly on its `RPAREN` so it stops at the `RPAREN` of `(W-IX)` in the if condition. Hence everything before was consumed in `EM` and `TO/INTO` is expected

**Comment by Claes65** [comment]
I guess the ‘).’ is just a string to be printed after the date. But I can see the trouble

**Comment by MarkusAmshove** [comment]
You can test #376 if you want, should resolve the issue :)

**Comment by Claes65** [comment]
Cool, first thing Monday. :) Have a nice weekend.
