### ISSUE TITLE
Hex strings and mixed hex and normal strings in continuations

### ISSUE THREAD

**Issue by Claes65** [MarkusAmshove/natls#345]
This is valid:
`DEFINE DATA LOCAL`
`1 #CONST (A20) INIT<H'ABCD'-`
`H'4040'`
`-H'F0F1'>`
`END-DEFINE`
Even this is valid (mixing string and hex string):
`DEFINE DATA LOCAL`
`1 #CONST (A20) INIT<H'ABCD'-`
`H'4040'`
`-'HELLO THERE'-`
`H'F0F1'>`
`END-DEFINE`

I was looking at consumeMinusOrStringConcat() and to extend it with looking at HEX_LITERALS as well. I got stuck when I figured out that the 2nd case is also valid. How can we support this? (The first case, I have diagnostics for). I think maybe consumeMinusOrStringConcat() could be simplified if we handle continued strings all at once (and not going back to main loop for every string).

**Comment by MarkusAmshove** [comment]
I might try to implement this in the parser where it parses string literals. Then the Lexer can still emit its tokens as is.

**Comment by Claes65** [comment]
Not sure I understand- but go for it. :)

**Comment by MarkusAmshove** [comment]
I've opened #355.
That handles string concat as a node type instead of handling it in the lexer :-)
