### ISSUE TITLE
NPP045 should be a Linter thing

### ISSUE THREAD

**Issue by Claes65** [MarkusAmshove/natls#347]
In my opinion :)

**Comment by Claes65** [comment]
Do you agree?  @MarkusAmshove then I can do this and use this NPP045 for my new NPP050 instead.

**Comment by MarkusAmshove** [comment]
Yeah, I can move it into a linter rule

**Comment by Claes65** [comment]
I’ll do it. ☺️

**Comment by Claes65** [comment]
Not sure what you mean? Maybe you should do it after all? ;)

**Comment by MarkusAmshove** [comment]
The current tests for this rule are in a resources file and not in a Java file I think.
So to identify the testcases you can write for the analyzer you can remove the reporting of this issue (there is only one place) and see which tests break to look at the source to get an idea for testcases.

But I can also do it if you want :-)

**Comment by Claes65** [comment]
Maybe it’s better if you do it.  But no rush. :)

**Comment by MarkusAmshove** [comment]
Is #394 ready to merge? I'll do the number adjustment after merging then, so the builds stay green :-)
