### ISSUE TITLE
Support for EM, HD, PM parameters for Field/Variable in DEFINE DATA

### ISSUE THREAD

**Issue by Claes65** [MarkusAmshove/natls#373]
https://documentation.softwareag.com/natural/nat912unx/sm/defineda_parms.htm#defineda_parms

**Comment by MarkusAmshove** [comment]
Do you have an example? Is this for INIT/CONST?

**Comment by Claes65** [comment]
emhdpm can follow a variable definition (also View fields) It’s a syntax after the INIT, see here: https://documentation.softwareag.com/natural/nat912unx/sm/defineda_vari.htm#defineda_vari

**Comment by Claes65** [comment]
@MarkusAmshove I can give this a try starting from tm. :)

**Comment by Claes65** [comment]
Closed by #394
