### ISSUE TITLE
Implicitly parse a copycode as part of the calling source

### ISSUE THREAD

**Issue by Claes65** [MarkusAmshove/natls#396]
Including nested copycodes. To avoid false diagnostics.

**Comment by MarkusAmshove** [comment]
This needs an example to reproduce, because nested copycodes work. You must hit some special case with parameters :-)

**Comment by Claes65** [comment]
The issue is the CC is parsed by itself and not as part of the including source. So the very simple example is a CC containing just

IF TRUE 

And then the including source will get flagged for an ENDIF without an IF.

**Comment by MarkusAmshove** [comment]
That needs a more biggy architectural change. I'm tracking this in the new issue #411
