### ISSUE TITLE
Restrict scope for data areas

### ISSUE THREAD

**Issue by MarkusAmshove** [MarkusAmshove/natls#40]
According to the documentation, only GDAs are allowed in GLOBAL USING scope.

LDAs and PDAs are allowed in both LOCAL and PARAMETER scope.

**Comment by Claes65** [comment]
@MarkusAmshove you can do LOCAL USING a PDA, however you cannot do a PARAMETER USING LDA. You are able to do the first, as the PDA can (should) be used in the CALLNAT/PERFORM from the caller, and the same PDA should be used in PARAMETER USING in the receiving module. That way, any changes in parameters will be made known in both modules after a recompile.
