### ISSUE TITLE
Linter: Disallow code between subroutines

### ISSUE THREAD

**Issue by Claes65** [MarkusAmshove/natls#464]
eg. this should not be allowed:
`DEFINE SUBROUTINE ABC`
...
`END-SUBROUTINE`
`PRINT 'Hello'`
`DEFINE SUBROUTINE XYZ`
...
`END-SUBROUTINE`
`END`
whereas this is fine:
`DEFINE SUBROUTINE ABC`
...
`END-SUBROUTINE`
`DEFINE SUBROUTINE XYZ`
...
`END-SUBROUTINE`
`PRINT 'Hello'`
`END`

**Comment by MarkusAmshove** [comment]
This should be configurable via editorconfig, e.g. `natls.style.disallowhangingstatements` (couldn't think of a better one yet :D) defaulting to `false`.

**Comment by Claes65** [comment]
Maybe `natls.style.disallowburiedstatements`?

**Comment by MarkusAmshove** [comment]
I like that :-)

**Comment by MarkusAmshove** [comment]
resolved by #498
