### ISSUE TITLE
Steplibs : doesn't work with a project managed by Natural Security

### ISSUE THREAD

**Issue by awilkins** [MarkusAmshove/natls#536]
Currently the LS reads the .natural file for information about steplibs ... a project with steplibs managed on the server by Natural Security looks like this ...

... the information must be cached somewhere, because I've started up NaturalONE this morning without a network connection to the server and the steplibs are still there in the library properties, so they can't possibly always come from the server ...

```xml
    <EnvironmentProperties>
        <SteplibNSV/>
        <SteplibExtensions>0;</SteplibExtensions>
        <LibrariesSteplibs/>
        <privateMode>false</privateMode>
        <Fuser>(0,0)</Fuser>
    </EnvironmentProperties>
    <NatsecRuntimeProfileLibrary>
        <NatsecLibrary>
            <NatsecLibraryName>MYLIB001</NatsecLibraryName>
            <NatsecLibraryFuser>(-1,-1)</NatsecLibraryFuser>
            <TerminalCommandChar>%</TerminalCommandChar>
            <TerminalCommandCharSwitch>true</TerminalCommandCharSwitch>
            <DecimalCharacter>.</DecimalCharacter>
            <FormatSpecify>false</FormatSpecify>
            <InputAssignCharacter>=</InputAssignCharacter>
            <InputDelimiterCharacter>,</InputDelimiterCharacter>
            <LineSize>0</LineSize>
            <ProcessingLoopLimit>99999999</ProcessingLoopLimit>
            <PageSize>0</PageSize>
            <SpacingFactor>1</SpacingFactor>
            <StructuredMode>true</StructuredMode>
            <LibraryPrivateMode>false</LibraryPrivateMode>
        </NatsecLibrary>

```

After a bit of hunting, I've found this information ... cached deep in the workspace metadata, and confirmed this by editing it.

ie it's in 
```
$WORKSPACE/.metadata/.plugins/org.eclipse.core.resources/.projects/$PROJECT/.indexes/properties.index
```
Also have no idea what the format is but it's binary and opaque.

Since most people wont check in this folder, and your workspace doesn't even have to be the parent folder of your project ... I think it might be nice to support a separate configuration file for these circumstances. Will have a look at maybe implementing one.

**Comment by MarkusAmshove** [comment]
We're also using Natural Security but have a `.natural` file which contains the steplib information (generated by NaturalONE).

It contains the `NatsecLibrary` (like yours) but also 
```
<EnvironmentProperties>
    <SteplibNSV/>
    <SteplibExtensions>0;</SteplibExtensions>
    <LibrariesSteplibs>
        <LibrarySteplib>
            <LibrarySteplibName>LIBNAME</LibrarySteplibName>
            <LibrarySteplibNSV>ANOTHERLIB</LibrarySteplibNSV>
            <LibrarySteplibExtensions>3;LIBONE[-1,-1];LIBTWO[-1,-1];LIBTHREE[-1,-1];</LibrarySteplibExtensions>
        </LibrarySteplib>
        ...
    </LibrariesSteplibs>
</EnvironmentProperties>
```

If I remember correctly it is generated when you open the properties of the project, go to Natural and say "save new defaults" or something like that.
Could also be that it is either generated together with the ANT script or that our users have more permissions for Natural Security.

**Comment by awilkins** [comment]
Hmm, yeah ; adding the steplibs from a container in which I'm admin, this part is populated, I've not seen it populated before.
Going to reconnect that project to the mainframe and see if it erases this section now ...

> Cannot read the library profile! Error LOGONUS 2602 NAT0807 Logon to this library is not permitted 

....

> error: User is not authorized to use this command : GLOBALS

... 

Changes all the Natsec libs but doesn't erase the ones in EnvironmentProperties at least.
