### ISSUE TITLE
Parse EXAMINE TRANSLATE

### ISSUE THREAD

**Issue by MarkusAmshove** [MarkusAmshove/natls#80]
The currently parsed `EXAMINE` doesn't allow `TRANSLATE`.

Example:

`EXAMINE SUBSTRING(WORK-FILE,14) TRANSLATE INTO LOWER CASE`

**Comment by Claes65** [comment]
I think it does? https://github.com/MarkusAmshove/natls/blob/d474b828444b9efbb031a673cddccfc337203e3a/libs/natparse/src/main/java/org/amshove/natparse/parsing/StatementListParser.java#LL2092C79-L2092C79

**Comment by Claes65** [comment]
Can't reproduce. Closed.

**Comment by MarkusAmshove** [comment]
examine translate is already implemented
